# ================================================================================
# OCI Object Storage — Upload SPA assets to the existing web bucket
# ================================================================================
# The bucket itself is created in 03-functions/storage.tf (backend phase) so the
# Identity Domains app can register its callback URL as an OAuth redirect.  This
# phase only uploads the generated SPA artifacts into that bucket:
#
#   index.html    generated from index.html.tmpl (API_BASE substituted by apply.sh)
#   config.json   generated by apply.sh (client_id + domain endpoints + redirect)
#   callback.html static PKCE code→token exchange page
#   favicon.ico   avoids browser 404s on the default icon request
#
# URL pattern:
#   https://objectstorage.{region}.oraclecloud.com/n/{namespace}/b/{bucket}/o/{object}
# ================================================================================

# Namespace is required to build the public Object Storage URL.
data "oci_objectstorage_namespace" "ns" {
  compartment_id = var.compartment_id
}

# --------------------------------------------------------------------------------
# index.html — generated from template by apply.sh before terraform apply
# --------------------------------------------------------------------------------
resource "oci_objectstorage_object" "index_html" {
  bucket        = var.web_bucket_name
  namespace     = data.oci_objectstorage_namespace.ns.namespace
  object        = "index.html"
  source        = "${path.module}/index.html"
  content_type  = "text/html"
  cache_control = "no-store, max-age=0"
}

# --------------------------------------------------------------------------------
# config.json — SPA runtime config (client_id, domain endpoints, redirect URI)
# --------------------------------------------------------------------------------
resource "oci_objectstorage_object" "config_json" {
  bucket        = var.web_bucket_name
  namespace     = data.oci_objectstorage_namespace.ns.namespace
  object        = "config.json"
  source        = "${path.module}/config.json"
  content_type  = "application/json"
  cache_control = "no-store, max-age=0"
}

# --------------------------------------------------------------------------------
# callback.html — PKCE redirect handler (exchanges auth code for tokens)
# --------------------------------------------------------------------------------
resource "oci_objectstorage_object" "callback_html" {
  bucket        = var.web_bucket_name
  namespace     = data.oci_objectstorage_namespace.ns.namespace
  object        = "callback.html"
  source        = "${path.module}/callback.html"
  content_type  = "text/html"
  cache_control = "no-store, max-age=0"
}

# --------------------------------------------------------------------------------
# favicon.ico — prevents browsers generating 404s on the default icon request
# --------------------------------------------------------------------------------
resource "oci_objectstorage_object" "favicon" {
  bucket        = var.web_bucket_name
  namespace     = data.oci_objectstorage_namespace.ns.namespace
  object        = "favicon.ico"
  source        = "${path.module}/favicon.ico"
  content_type  = "image/x-icon"
  cache_control = "no-store, max-age=0"
}

# --------------------------------------------------------------------------------
# Output — direct HTTPS link to the hosted index.html
# --------------------------------------------------------------------------------
output "website_url" {
  description = "Direct HTTPS link to the Notes web application"
  value = join("", [
    "https://objectstorage.${var.region}.oraclecloud.com",
    "/n/${data.oci_objectstorage_namespace.ns.namespace}",
    "/b/${var.web_bucket_name}",
    "/o/index.html",
  ])
}
