# ================================================================================
# OCI Object Storage — upload the SPA into the existing web bucket
# ================================================================================
# The bucket itself is created in 03-functions/storage.tf (backend phase) so the
# Identity Domains app can register its callback URL as an OAuth redirect. This
# phase only uploads.
#
# Uploads are discovered with a fileset rather than listed one resource per
# file. The SPA is sixteen files across css/ and js/, and a hand-maintained list
# silently stops deploying whatever gets added to it later — the failure being a
# 404 on one asset rather than an error at apply time.
#
# js/config.js is generated by apply.sh from js/config.js.tmpl before this runs,
# so it appears in the fileset like any other asset.
#
# URL pattern:
#   https://objectstorage.{region}.oraclecloud.com/n/{namespace}/b/{bucket}/o/{object}
# ================================================================================

# Namespace is required to build the public Object Storage URL.
data "oci_objectstorage_namespace" "ns" {
  compartment_id = var.compartment_id
}

locals {
  # Explicit patterns, NOT a bare "**" glob. The Terraform files live in this
  # same directory, and the bucket is public-read — a recursive glob would
  # publish main.tf, storage.tf and the .terraform state directory to the
  # internet. Only the browser assets are eligible.
  #
  # js/config.js.tmpl is excluded: shipping the unrendered template alongside
  # the real config would expose the placeholder names for no benefit.
  web_files = setsubtract(
    setunion(
      fileset(path.module, "*.html"),
      fileset(path.module, "*.ico"),
      fileset(path.module, "css/*"),
      fileset(path.module, "js/*.js"),
    ),
    ["js/config.js.tmpl"]
  )

  # Object Storage does not infer Content-Type, and a stylesheet or module
  # served as application/octet-stream is ignored by the browser: the page
  # renders unstyled and the app never boots.
  content_types = {
    html = "text/html"
    js   = "text/javascript"
    css  = "text/css"
    ico  = "image/x-icon"
    json = "application/json"
    png  = "image/png"
    svg  = "image/svg+xml"
  }
}

# --------------------------------------------------------------------------------
# SPA assets
# --------------------------------------------------------------------------------
# cache_control is no-store throughout. The bundle is tiny and the config file
# carries deploy-specific values, so a cached config.js from a previous deploy
# would point the app at a torn-down API.
# --------------------------------------------------------------------------------
resource "oci_objectstorage_object" "web" {
  for_each = local.web_files

  bucket    = var.web_bucket_name
  namespace = data.oci_objectstorage_namespace.ns.namespace
  object    = each.value
  source    = "${path.module}/${each.value}"

  content_type = lookup(
    local.content_types,
    lower(reverse(split(".", each.value))[0]),
    "application/octet-stream"
  )

  cache_control = "no-store, max-age=0"
}

# --------------------------------------------------------------------------------
# Output — direct HTTPS link to the hosted index.html
# --------------------------------------------------------------------------------
output "website_url" {
  description = "Direct HTTPS link to the resume scoring web application"
  value = join("", [
    "https://objectstorage.${var.region}.oraclecloud.com",
    "/n/${data.oci_objectstorage_namespace.ns.namespace}",
    "/b/${var.web_bucket_name}",
    "/o/index.html",
  ])
}
