# ================================================================================
# Jobs API
#
# Handles CRUD operations for job scoring objects.
#
# Design
# - Job metadata stored in NoSQL
# - Job-owned text artifacts stored in Object Storage at deterministic names
# - Resume snapshot written at job creation, so a later resume edit cannot
#   retroactively change what a past score was computed against
# - Job description stored when provided as raw text, or later by the worker
#   once it has scraped the URL
# - Job analysis stored when generated by the model
# - Notes are the only mutable field
#
# NoSQL keys
#   pk = <user_id>   (bare subject — see the key budget in common.py)
#   sk = JOB#<job_id>
#
# Object Storage layout
#   users/USER#<user_id>/jobs/JOB#<job_id>/resume_snapshot.txt
#   users/USER#<user_id>/jobs/JOB#<job_id>/job_description.txt
#   users/USER#<user_id>/jobs/JOB#<job_id>/job_analysis.txt
#   users/USER#<user_id>/jobs/JOB#<job_id>/notes.txt
#   users/USER#<user_id>/jobs/JOB#<job_id>/attachments/<att_id>/<filename>
# ================================================================================

import json
import logging

import nosql_util
import os_util
from common import QUEUE_ENDPOINT, QUEUE_ID, SIGNER
from common import ok, error, new_id, user_pk, utc_now

from oci.queue import QueueClient
from oci.queue.models import PutMessagesDetails, PutMessagesDetailsEntry

log = logging.getLogger(__name__)

# Lifetime caps. The token cap is 500k here rather than the AWS build's 100k:
# gpt-oss-120b is a reasoning model, so chain-of-thought it never shows the
# user still bills as output tokens and burns the allowance several times
# faster for the same visible analysis.
MAX_JOBS_PER_USER   = 1000
TOKEN_LIMIT_DEFAULT = 500_000

# --------------------------------------------------------------------------------
# Queue client
# --------------------------------------------------------------------------------
# Unlike every other OCI service client, the Queue data plane is addressed at a
# per-queue endpoint rather than the regional one, so service_endpoint is
# mandatory here. Terraform passes it through as QUEUE_ENDPOINT; without it the
# SDK targets the control plane and every put_messages call 404s.
# --------------------------------------------------------------------------------
_queue = QueueClient(
    config={},
    signer=SIGNER,
    service_endpoint=QUEUE_ENDPOINT,
) if QUEUE_ENDPOINT else None


# --------------------------------------------------------------------------------
# Function: build_job_paths
#
# Purpose
# Derives NoSQL keys and all Object Storage names for a given user/job pair.
#
# Arguments
# - user_id : authenticated user identifier
# - job_id  : UUID of the job record
#
# Returns
# - dict with pk, sk, and per-artifact object names
# --------------------------------------------------------------------------------
def build_job_paths(user_id, job_id):
    return {
        "pk": user_pk(user_id),
        "sk": f"JOB#{job_id}",
        "prefix":              os_util.job_prefix(user_id, job_id),
        "resume_snapshot_key": os_util.resume_snapshot_key(user_id, job_id),
        "job_description_key": os_util.job_description_key(user_id, job_id),
        "job_analysis_key":    os_util.job_analysis_key(user_id, job_id),
        "notes_key":           os_util.notes_key(user_id, job_id),
    }


# --------------------------------------------------------------------------------
# Function: enqueue_job_request
#
# Purpose
# Sends a scoring request to the OCI Queue. Connector Hub drains the queue and
# invokes the worker function.
#
# Arguments
# - user_id     : authenticated user identifier
# - job_id      : UUID of the job record
# - resume_id   : UUID of the resume to score against
# - source_type : "url" or "raw_text"
# - job_url     : URL to fetch for URL-type jobs, empty string otherwise
# --------------------------------------------------------------------------------
def enqueue_job_request(user_id, job_id, resume_id, source_type, job_url):
    message = {
        "user_id":     user_id,
        "job_id":      job_id,
        "resume_id":   resume_id,
        "source_type": source_type,
        "job_url":     job_url,
    }

    # OCI Queue message content is a plain string — unlike SQS there is no
    # separate attribute map, so the whole request travels as JSON in content.
    _queue.put_messages(
        queue_id=QUEUE_ID,
        put_messages_details=PutMessagesDetails(
            messages=[PutMessagesDetailsEntry(content=json.dumps(message))]
        ),
    )


# ------------------------------------------------------------------------------
# POST /jobs
#
# Creates a job scoring record.
# ------------------------------------------------------------------------------

def create_job(req):

    user_id = req.require_user()
    pk      = user_pk(user_id)

    resume_id       = (req.body.get("resume_id") or "").strip()
    source_type     = (req.body.get("source_type") or "").strip()
    job_url         = (req.body.get("job_url") or "").strip()
    job_description = (req.body.get("job_description") or "").strip()
    notes           = (req.body.get("notes") or "").strip()
    folder_id       = (req.body.get("folder_id") or "").strip() or None

    # Reject if the user has hit the lifetime job cap.
    if len(nosql_util.query_items(pk, "JOB#")) >= MAX_JOBS_PER_USER:
        return error(
            429,
            "Job limit reached. Maximum 1,000 scored jobs per account."
        )

    # Check the token budget before accepting the job — rejecting here means the
    # user sees a clear error in the submit dialog rather than a job that sits
    # at "submitted" forever because the worker refused it.
    usage       = nosql_util.get_item(pk, "USER#USAGE") or {}
    tokens_used = int(usage.get("tokens_used", 0) or 0)
    token_limit = int(
        usage.get("token_limit", TOKEN_LIMIT_DEFAULT) or TOKEN_LIMIT_DEFAULT
    )
    if tokens_used >= token_limit:
        return error(
            429, "Token limit reached. Please contact the administrator."
        )

    if not resume_id:
        return error(400, "resume_id is required")

    if source_type not in ["url", "raw_text"]:
        return error(400, "source_type must be 'url' or 'raw_text'")

    if source_type == "url" and not job_url:
        return error(400, "job_url is required")

    if source_type == "raw_text" and not job_description:
        return error(400, "job_description is required")

    # --------------------------------------------------------------------------
    # Validate resume exists
    # --------------------------------------------------------------------------

    resume_item = nosql_util.get_item(pk, f"RESUME#{resume_id}")
    if not resume_item:
        return error(404, "resume not found")

    # --------------------------------------------------------------------------
    # Create job identifiers and paths
    # --------------------------------------------------------------------------

    job_id = new_id()
    paths  = build_job_paths(user_id, job_id)
    now    = utc_now()

    # --------------------------------------------------------------------------
    # Copy resume snapshot into the job's prefix
    # --------------------------------------------------------------------------

    resume_text = os_util.read_text(resume_item.get("object_name", ""))
    os_util.write_text(paths["resume_snapshot_key"], resume_text)

    # --------------------------------------------------------------------------
    # Store job description when provided as raw text
    # --------------------------------------------------------------------------

    if source_type == "raw_text":
        os_util.write_text(paths["job_description_key"], job_description)

    # --------------------------------------------------------------------------
    # Store notes when provided
    # --------------------------------------------------------------------------

    if notes:
        os_util.write_text(paths["notes_key"], notes)

    # --------------------------------------------------------------------------
    # Write metadata
    # --------------------------------------------------------------------------

    item = {
        "resume_id":      resume_id,
        "source_type":    source_type,
        "job_url":        job_url if source_type == "url" else "",
        "status":         "submitted",
        "status_message": "Job submitted for scoring",
        "job_title":      "",
        "company":        "",
        "score":          None,
        "created_at":     now,
        "updated_at":     now,
    }
    if folder_id:
        item["folder_id"] = folder_id

    nosql_util.put_item(pk, paths["sk"], item)

    # --------------------------------------------------------------------------
    # Enqueue scoring request
    # --------------------------------------------------------------------------
    # The job row is written first and the message second, so a failed enqueue
    # leaves a visible job in queue_error rather than a silent no-op. The
    # inverse order would risk the worker picking up a job whose row does not
    # exist yet.
    # --------------------------------------------------------------------------

    try:
        enqueue_job_request(
            user_id=user_id,
            job_id=job_id,
            resume_id=resume_id,
            source_type=source_type,
            job_url=job_url if source_type == "url" else "",
        )
    except Exception as exc:
        log.exception("failed to enqueue job %s", job_id)

        def mark_failed(it):
            it["status"]         = "queue_error"
            it["status_message"] = "Failed to enqueue scoring request"
            it["updated_at"]     = utc_now()

        nosql_util.update_doc(pk, paths["sk"], mark_failed)

        return 500, {
            "error":   "failed to enqueue scoring request",
            "details": str(exc),
        }

    return ok({
        "job_id":         job_id,
        "status":         "submitted",
        "status_message": "Job submitted for scoring",
    })


# ------------------------------------------------------------------------------
# GET /jobs
#
# Returns job metadata for the current user.
# ------------------------------------------------------------------------------

def list_jobs(req):

    items = nosql_util.query_items(req.pk, "JOB#")

    jobs = [
        {
            "job_id":         item["sk"].replace("JOB#", "", 1),
            "resume_id":      item.get("resume_id"),
            "status":         item.get("status"),
            "status_message": item.get("status_message"),
            "job_title":      item.get("job_title"),
            "company":        item.get("company"),
            "job_url":        item.get("job_url", ""),
            "folder_id":      item.get("folder_id") or "",
            "score":          item.get("score"),
            "created_at":     item.get("created_at"),
            "updated_at":     item.get("updated_at"),
            # Avoids extra fetches in the dashboard clip button logic
            "attachment_count": len(item.get("attachments") or []),
        }
        for item in items
    ]

    return ok(jobs)


# ------------------------------------------------------------------------------
# GET /jobs/{job_id}
#
# Returns job metadata and job-owned text artifacts.
# ------------------------------------------------------------------------------

def get_job(req):

    user_id = req.require_user()
    job_id  = req.job_id

    if not job_id:
        return error(400, "job_id is required")

    item = nosql_util.get_item(user_pk(user_id), f"JOB#{job_id}")
    if not item:
        return error(404, "job not found")

    paths = build_job_paths(user_id, job_id)

    return ok({
        "job_id":          job_id,
        "resume_id":       item.get("resume_id"),
        "source_type":     item.get("source_type"),
        "job_url":         item.get("job_url"),
        "status":          item.get("status"),
        "status_message":  item.get("status_message"),
        "job_title":       item.get("job_title", ""),
        "company":         item.get("company", ""),
        "score":           item.get("score"),
        "resume_snapshot": os_util.read_text(paths["resume_snapshot_key"]),
        "job_description": os_util.read_text(paths["job_description_key"]),
        "job_analysis":    os_util.read_text(paths["job_analysis_key"]),
        "folder_id":       item.get("folder_id", ""),
        "notes":           os_util.read_text(paths["notes_key"]),
        "created_at":      item.get("created_at"),
        "updated_at":      item.get("updated_at"),
    })


# ------------------------------------------------------------------------------
# PATCH /jobs/{job_id}/notes
#
# Updates notes only. All other job fields are immutable.
# ------------------------------------------------------------------------------

def update_job_notes(req):

    user_id = req.require_user()
    job_id  = req.job_id

    if not job_id:
        return error(400, "job_id is required")

    notes = (req.body.get("notes") or "").strip()

    paths = build_job_paths(user_id, job_id)

    item = nosql_util.get_item(paths["pk"], paths["sk"])
    if not item:
        return error(404, "job not found")

    # Empty notes delete the object rather than storing a blank one, so
    # "no notes" is one state rather than two.
    if notes:
        os_util.write_text(paths["notes_key"], notes)
    else:
        os_util.delete_object(paths["notes_key"])

    nosql_util.update_doc(
        paths["pk"], paths["sk"],
        lambda it: it.__setitem__("updated_at", utc_now())
    )

    return ok({"updated": True})


# ------------------------------------------------------------------------------
# PATCH /jobs/{job_id}/folder
#
# Moves a job into a folder or removes it from its current folder.
# ------------------------------------------------------------------------------

def move_job_to_folder(req):

    user_id = req.require_user()
    job_id  = req.job_id

    if not job_id:
        return error(400, "job_id is required")

    paths = build_job_paths(user_id, job_id)

    item = nosql_util.get_item(paths["pk"], paths["sk"])
    if not item:
        return error(404, "job not found")

    folder_id = (req.body.get("folder_id") or "").strip() or None

    def apply(it):
        if folder_id:
            it["folder_id"] = folder_id
        else:
            # Drop the key entirely so "missing" and "unassigned" are the same
            # state, matching the REMOVE the AWS version issues.
            it.pop("folder_id", None)
        it["updated_at"] = utc_now()

    nosql_util.update_doc(paths["pk"], paths["sk"], apply)

    return ok({"job_id": job_id, "folder_id": folder_id})


# ------------------------------------------------------------------------------
# DELETE /jobs/{job_id}
#
# Deletes job metadata and every object under the job's prefix.
# ------------------------------------------------------------------------------

def delete_job(req):

    user_id = req.require_user()
    job_id  = req.job_id

    if not job_id:
        return error(400, "job_id is required")

    paths = build_job_paths(user_id, job_id)

    item = nosql_util.get_item(paths["pk"], paths["sk"])
    if not item:
        return error(404, "job not found")

    # Prefix delete rather than naming the four text artifacts individually:
    # that misses the attachments/ subtree, which would leave orphaned blobs
    # behind with nothing left pointing at them.
    os_util.delete_prefix(paths["prefix"])

    nosql_util.delete_item(paths["pk"], paths["sk"])

    return ok({"deleted": True})
